spanner:
  instance:
    id: instance-1
  database:
    id: database-1
  project:
    id: sab-ors-poc-sbx-01-9096

GOOGLE_APPLICATION_CREDENTIALS: ./cred.json

max:
  version:
    replicate: 3
  data:
    limit: 70

scheduler:
  pool:
    size: 50
  delay:
    interval: 60   # In sec


tps: 50


